db.createUser({
  user: 'lotto',
  pwd: 'lotto',
  roles: [
    {
      role: 'readWrite',
      db: 'Lotto',
    },
  ],
});

db.createCollection('Players');
db.createCollection('AdminRoles');
db.createCollection('AdminUsers');
db.createCollection('Avatars');
db.createCollection('Domains');
db.createCollection('States');
db.createCollection('Settings');
db.createCollection('Tickets');
db.createCollection('Subtickets');
db.createCollection('HistoricTickets');
db.createCollection('NumberLimits');
db.createCollection('Games');
db.createCollection('GradingResults');
db.createCollection('Profiles');
db.createCollection('Transactions');
db.createCollection('WinnersBanner');
db.createCollection('Feedback');

db.Players.createIndex({ playerId: -1 });
db.Players.createIndex({ gbsId: -1 });
db.Domains.createIndex({ url: +1 });
db.States.createIndex({ abbreviation: +1 });
db.Games.createIndex({ gameId: +1 });
db.GradingResults.createIndex({ drawDate: -1, state: 1, gameType: 1 });
db.GradingResults.createIndex({ drawDate: -1 });
db.GradingResults.createIndex({ state: 1 });
db.NumberLimits.createIndex({ state: 1, hour: 1 });
db.NumberLimits.createIndex({ gameType: 1 });
db.NumberLimits.createIndex({ drawDate: -1 });
db.NumberLimits.createIndex({ number: -1 });
db.Tickets.createIndex({ gameType: 1 });
db.Tickets.createIndex({ orderNumber: 1 });
db.Tickets.createIndex({ dates: 1 });
db.Tickets.createIndex({ 'draws.hour': 1, 'draws.state': 1 });
db.Tickets.createIndex({ ticketNumber: 1 });
db.Tickets.createIndex({ playerId: -1 });
db.Subtickets.createIndex({ playerId: -1 });
db.Subtickets.createIndex({ ticketNumber: -1 });
db.Subtickets.createIndex({ drawDate: -1 });
db.Subtickets.createIndex({ state: 1, hour: 1 });
db.Subtickets.createIndex({ gameType: 1 });
db.Subtickets.createIndex({ ruleType: 1 });
db.Subtickets.createIndex({ number: 1 });
db.HistoricTickets.createIndex({ date: 1 });
db.HistoricTickets.createIndex({ date: 1, playerId: 1 });
db.Transactions.createIndex({ date: 1, currencyCode: -1 });
db.Transactions.createIndex({ transactionNumber: 1 });
db.Transactions.createIndex({ date: 1 });

db.Games.insertMany([
  {
    gameId: '2',
    betAmounts: [0.25, 0.5, 0.75, 1, 2, 5, 50, 100, 500, 750, 1000, 1111.11],
    draws: [
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '9:15 PM',
        description: 'FL Evening 9:15 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '7:20 PM',
        description: 'DC Evening 7:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '1:20 PM',
        description: 'DC Midday 1:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '1:00 PM',
        description: 'FL Midday 1:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ON',
        scheduledHour: '1:40 PM',
        description: 'ON Midday 1:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ON',
        scheduledHour: '10:10 PM',
        description: 'ON Night 10:10 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '1:05 PM',
        description: 'PA Midday 1:05 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '6:29 PM',
        description: 'PA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PR',
        scheduledHour: '9:00 AM',
        description: 'PR Midday 9:00 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PR',
        scheduledHour: '4:00 PM',
        description: 'PR Evening 4:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'QC',
        scheduledHour: '10:00 PM',
        description: 'QC Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WC',
        scheduledHour: '10:00 PM',
        description: 'WC Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
    ],
    log: [],
  },
  {
    gameId: '3',
    betAmounts: [0.25, 0.5, 0.75, 1, 2, 5, 10, 25, 50, 75, 100, 111],
    draws: [
      {
        _id: ObjectId(),
        state: 'AR',
        scheduledHour: '7:29 PM',
        description: 'AR Evening 7:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'AZ',
        scheduledHour: '9:29 PM',
        description: 'AZ Night 9:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '9:15 PM',
        description: 'FL Evening 9:15 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '1:00 PM',
        description: 'FL Midday 1:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'AR',
        scheduledHour: '1:29 PM',
        description: 'AR Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CA',
        scheduledHour: '3:30 PM',
        description: 'CA Midday 3:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CA',
        scheduledHour: '9:00 PM',
        description: 'CA Evening 9:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CO',
        scheduledHour: '3:06 PM',
        description: 'CO Midday 3:06 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CO',
        scheduledHour: '9:00 PM',
        description: 'CO Evening 9:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CT',
        scheduledHour: '1:27 PM',
        description: 'CT Midday 1:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CT',
        scheduledHour: '9:59 PM',
        description: 'CT Night 9:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '1:20 PM',
        description: 'DC Midday 1:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '7:20 PM',
        description: 'DC Evening 7:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '11:00 PM',
        description: 'DC Night 11:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DE',
        scheduledHour: '1:28 PM',
        description: 'DE Midday 1:28 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DE',
        scheduledHour: '7:27 PM',
        description: 'DE Evening 7:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '11:59 AM',
        description: 'GA Midday 11:59 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '6:29 PM',
        description: 'GA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '11:04 PM',
        description: 'GA Night 11:04 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IA',
        scheduledHour: '12:50 PM',
        description: 'IA Midday 12:50 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IA',
        scheduledHour: '10:30 PM',
        description: 'IA Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ID',
        scheduledHour: '3:29 PM',
        description: 'ID Midday 3:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ID',
        scheduledHour: '9:29 PM',
        description: 'ID Evening 9:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IL',
        scheduledHour: '1:10 PM',
        description: 'IL Midday 1:10 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IL',
        scheduledHour: '9:52 PM',
        description: 'IL Night 9:52 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IN',
        scheduledHour: '12:30 PM',
        description: 'IN Midday 12:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IN',
        scheduledHour: '10:30 PM',
        description: 'IN Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'KS',
        scheduledHour: '1:40 PM',
        description: 'KS Midday 1:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'KS',
        scheduledHour: '9:40 PM',
        description: 'KS Evening 9:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'KY',
        scheduledHour: '12:50 PM',
        description: 'KY Midday 12:50 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'KY',
        scheduledHour: '10:30 PM',
        description: 'KY Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'LA',
        scheduledHour: '10:29 PM',
        description: 'LA Night 10:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MI',
        scheduledHour: '12:29 PM',
        description: 'MI Midday 12:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MI',
        scheduledHour: '6:59 PM',
        description: 'MI Evening 6:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MN',
        scheduledHour: '6:47 PM',
        description: 'MN Evening 6:47 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MO',
        scheduledHour: '1:29 PM',
        description: 'MO Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MO',
        scheduledHour: '9:45 PM',
        description: 'MO Night 9:45 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MS',
        scheduledHour: '3:00 PM',
        description: 'MS Midday 3:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MS',
        scheduledHour: '10:00 PM',
        description: 'MS Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NC',
        scheduledHour: '2:30 PM',
        description: 'NC Midday 2:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NC',
        scheduledHour: '10:52 PM',
        description: 'NC Night 10:52 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NE',
        scheduledHour: '9:30 PM',
        description: 'NE Evening 9:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NH',
        scheduledHour: '12:40 PM',
        description: 'ME, NH & VT Midday 12:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NH',
        scheduledHour: '6:25 PM',
        description: 'ME, NH & VT Evening 6:25 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NJ',
        scheduledHour: '12:29 PM',
        description: 'NJ Midday 12:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NJ',
        scheduledHour: '10:27 PM',
        description: 'NJ Night 10:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NM',
        scheduledHour: '2:30 PM',
        description: 'NM Midday 2:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NM',
        scheduledHour: '11:00 PM',
        description: 'NM Night 11:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NY',
        scheduledHour: '10:00 PM',
        description: 'NY Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NY',
        scheduledHour: '2:00 PM',
        description: 'NY Midday 2:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OH',
        scheduledHour: '11:59 AM',
        description: 'OH Midday 11:59 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OH',
        scheduledHour: '6:59 PM',
        description: 'OH Evening 6:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OK',
        scheduledHour: '9:30 PM',
        description: 'OK Evening 9:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ON',
        scheduledHour: '1:40 PM',
        description: 'ON Midday 1:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ON',
        scheduledHour: '10:10 PM',
        description: 'ON Night 10:10 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '1:05 PM',
        description: 'PA Midday 1:05 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '6:29 PM',
        description: 'PA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PR',
        scheduledHour: '9:00 AM',
        description: 'PR Midday 9:00 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PR',
        scheduledHour: '4:00 PM',
        description: 'PR Evening 4:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'QC',
        scheduledHour: '10:00 PM',
        description: 'QC Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'SC',
        scheduledHour: '12:29 PM',
        description: 'SC Midday 12:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'SC',
        scheduledHour: '6:29 PM',
        description: 'SC Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TN',
        scheduledHour: '9:58 AM',
        description: 'TN Morning 9:58 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TN',
        scheduledHour: '12:58 PM',
        description: 'TN Midday 12:58 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TN',
        scheduledHour: '6:58 PM',
        description: 'TN Evening 6:58 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '10:30 AM',
        description: 'TX Morning 10:30 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '12:57 PM',
        description: 'TX Midday 12:57 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '6:30 PM',
        description: 'TX Evening 6:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '10:42 PM',
        description: 'TX Night 10:42 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'VA',
        scheduledHour: '1:29 PM',
        description: 'VA Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'VA',
        scheduledHour: '10:30 PM',
        description: 'VA Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WA',
        scheduledHour: '10:30 PM',
        description: 'WA Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WC',
        scheduledHour: '10:00 PM',
        description: 'WC Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WI',
        scheduledHour: '2:00 PM',
        description: 'WI Midday 2:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WI',
        scheduledHour: '9:30 PM',
        description: 'WI Evening 9:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 600,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WV',
        scheduledHour: '6:29 PM',
        description: 'WV Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 600,
        log: [],
      },
    ],
    log: [],
  },
  {
    gameId: '4',
    betAmounts: [0.25, 0.5, 0.75, 1, 1.5, 2, 3, 4, 5, 7.5, 10, 11.11],
    draws: [
      {
        _id: ObjectId(),
        state: 'AC',
        scheduledHour: '10:00 PM',
        description: 'A. Canada Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '9:15 PM',
        description: 'FL Evening 9:15 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '1:00 PM',
        description: 'FL Midday 1:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'AR',
        scheduledHour: '1:29 PM',
        description: 'AR Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'AR',
        scheduledHour: '7:29 PM',
        description: 'AR Evening 7:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CA',
        scheduledHour: '9:00 PM',
        description: 'CA Evening 9:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CT',
        scheduledHour: '1:27 PM',
        description: 'CT Midday 1:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'CT',
        scheduledHour: '9:59 PM',
        description: 'CT Night 9:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '1:20 PM',
        description: 'DC Midday 1:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '7:20 PM',
        description: 'DC Evening 7:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '11:00 PM',
        description: 'DC Night 11:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DE',
        scheduledHour: '1:28 PM',
        description: 'DE Midday 1:28 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DE',
        scheduledHour: '7:27 PM',
        description: 'DE Evening 7:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '11:59 AM',
        description: 'GA Midday 11:59 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '6:29 PM',
        description: 'GA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '11:04 PM',
        description: 'GA Night 11:04 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IA',
        scheduledHour: '12:50 PM',
        description: 'IA Midday 12:50 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IA',
        scheduledHour: '10:30 PM',
        description: 'IA Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ID',
        scheduledHour: '3:29 PM',
        description: 'ID Midday 3:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ID',
        scheduledHour: '9:29 PM',
        description: 'ID Evening 9:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IL',
        scheduledHour: '1:10 PM',
        description: 'IL Midday 1:10 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IL',
        scheduledHour: '9:52 PM',
        description: 'IL Night 9:52 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IN',
        scheduledHour: '12:30 PM',
        description: 'IN Midday 12:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'IN',
        scheduledHour: '10:30 PM',
        description: 'IN Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'KY',
        scheduledHour: '12:50 PM',
        description: 'KY Midday 12:50 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'KY',
        scheduledHour: '10:30 PM',
        description: 'KY Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'LA',
        scheduledHour: '10:29 PM',
        description: 'LA Night 10:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MA',
        scheduledHour: '1:30 PM',
        description: 'MA Midday 1:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MA',
        scheduledHour: '8:30 PM',
        description: 'MA Evening 8:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MI',
        scheduledHour: '12:29 PM',
        description: 'MI Midday 12:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MI',
        scheduledHour: '6:59 PM',
        description: 'MI Evening 6:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MO',
        scheduledHour: '1:29 PM',
        description: 'MO Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MO',
        scheduledHour: '9:45 PM',
        description: 'MO Night 9:45 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MS',
        scheduledHour: '3:00 PM',
        description: 'MS Midday 3:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'MS',
        scheduledHour: '10:00 PM',
        description: 'MS Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NC',
        scheduledHour: '2:30 PM',
        description: 'NC Midday 2:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NC',
        scheduledHour: '10:52 PM',
        description: 'NC Night 10:52 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NH',
        scheduledHour: '12:40 PM',
        description: 'ME, NH & VT Midday 12:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NH',
        scheduledHour: '6:25 PM',
        description: 'ME, NH & VT Evening 6:25 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NJ',
        scheduledHour: '12:29 PM',
        description: 'NJ Midday 12:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NJ',
        scheduledHour: '10:27 PM',
        description: 'NJ Night 10:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NM',
        scheduledHour: '2:30 PM',
        description: 'NM Midday 2:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NM',
        scheduledHour: '11:00 PM',
        description: 'NM Night 11:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NY',
        scheduledHour: '2:00 PM',
        description: 'NY Midday 2:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'NY',
        scheduledHour: '10:00 PM',
        description: 'NY Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OH',
        scheduledHour: '11:59 AM',
        description: 'OH Midday 11:59 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OH',
        scheduledHour: '6:59 PM',
        description: 'OH Evening 6:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ON',
        scheduledHour: '1:40 PM',
        description: 'ON Midday 1:40 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'ON',
        scheduledHour: '10:10 PM',
        description: 'ON Night 10:10 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OR',
        scheduledHour: '3:30 PM',
        description: 'OR Midday 3:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OR',
        scheduledHour: '6:30 PM',
        description: 'OR Afternoon 6:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OR',
        scheduledHour: '9:30 PM',
        description: 'OR Evening 9:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OR',
        scheduledHour: '11:59 PM',
        description: 'OR Night 11:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '1:05 PM',
        description: 'PA Midday 1:05 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '6:29 PM',
        description: 'PA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PR',
        scheduledHour: '9:00 AM',
        description: 'PR Midday 9:00 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PR',
        scheduledHour: '4:00 PM',
        description: 'PR Evening 4:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'QC',
        scheduledHour: '10:00 PM',
        description: 'QC Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'RI',
        scheduledHour: '1:00 PM',
        description: 'RI Midday 1:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'RI',
        scheduledHour: '6:59 PM',
        description: 'RI Evening 6:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'SC',
        scheduledHour: '12:29 PM',
        description: 'SC Midday 12:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'SC',
        scheduledHour: '6:29 PM',
        description: 'SC Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TN',
        scheduledHour: '9:58 AM',
        description: 'TN Morning 9:58 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TN',
        scheduledHour: '12:58 PM',
        description: 'TN Midday 12:58 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TN',
        scheduledHour: '6:58 PM',
        description: 'TN Evening 6:58 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '10:30 AM',
        description: 'TX Morning 10:30 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '12:57 PM',
        description: 'TX Midday 12:57 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '6:30 PM',
        description: 'TX Evening 6:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'TX',
        scheduledHour: '10:42 PM',
        description: 'TX Night 10:42 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'VA',
        scheduledHour: '1:29 PM',
        description: 'VA Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'VA',
        scheduledHour: '10:30 PM',
        description: 'VA Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WC',
        scheduledHour: '10:00 PM',
        description: 'WC Night 10:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WI',
        scheduledHour: '2:00 PM',
        description: 'WI Midday 2:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WI',
        scheduledHour: '9:30 PM',
        description: 'WI Evening 9:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 100,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'WV',
        scheduledHour: '6:29 PM',
        description: 'WV Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6],
        limit: 100,
        log: [],
      },
    ],
    log: [],
  },
  {
    gameId: '5',
    betAmounts: [0.25, 0.3, 0.4, 0.5, 0.6, 0.75, 1, 1.11],
    draws: [
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '9:15 PM',
        description: 'FL Evening 9:15 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'FL',
        scheduledHour: '1:00 PM',
        description: 'FL Midday 1:00 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '1:20 PM',
        description: 'DC Midday 1:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DC',
        scheduledHour: '7:20 PM',
        description: 'DC Evening 7:20 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DE',
        scheduledHour: '1:28 PM',
        description: 'DE Midday 1:28 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'DE',
        scheduledHour: '7:27 PM',
        description: 'DE Evening 7:27 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '11:59 AM',
        description: 'GA Midday 11:59 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'GA',
        scheduledHour: '6:29 PM',
        description: 'GA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'LA',
        scheduledHour: '10:29 PM',
        description: 'LA Night 10:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OH',
        scheduledHour: '11:59 AM',
        description: 'OH Midday 11:59 AM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'OH',
        scheduledHour: '6:59 PM',
        description: 'OH Evening 6:59 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '1:05 PM',
        description: 'PA Midday 1:05 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'PA',
        scheduledHour: '6:29 PM',
        description: 'PA Evening 6:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'VA',
        scheduledHour: '1:29 PM',
        description: 'VA Midday 1:29 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
      {
        _id: ObjectId(),
        state: 'VA',
        scheduledHour: '10:30 PM',
        description: 'VA Night 10:30 PM',
        disabledIn: [],
        daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
        limit: 12,
        log: [],
      },
    ],
  },
]);

db.Players.insertMany([
  {
    playerId: 'B52366',
    gbsId: 'B52366',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'BA8',
    gbsId: 'BA8',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'XYZ720',
    gbsId: 'XYZ720',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'LMN999',
    gbsId: 'LMN999',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'PQR123',
    gbsId: 'PQR123',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'ABC456',
    gbsId: 'ABC456',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'DEF789',
    gbsId: 'DEF789',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'GHI321',
    gbsId: 'GHI321',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'JKL654',
    gbsId: 'JKL654',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
  {
    playerId: 'MNO777',
    gbsId: 'MNO777',
    avatar: '',
    rewardBalance: 100,
    notifications: [],
    joinDate: ISODate('1970-01-01T00:00:00.000Z'),
    nickName: 'Lotto',
    profile: '',
    preferences: {
      draws: [
        {
          state: 'AC',
          hour: '10:15 PM',
          gameType: '4',
        },
      ],
      preferences: [
        {
          key: 'FirstGameToPlay',
          isEnabled: false,
          value: 'Pick',
          optionsSelected: [],
        },
        {
          key: 'LobbyView',
          isEnabled: false,
          value: 'NewView',
          optionsSelected: [],
        },
        {
          key: 'GameType',
          isEnabled: false,
          value: 'Pick3',
          optionsSelected: [],
        },
        {
          key: 'PickMode',
          isEnabled: false,
          value: 'Balls',
          optionsSelected: [],
        },
        {
          key: 'QuickPick',
          isEnabled: false,
          value: 'OneDrawDifferentNumber',
          optionsSelected: [],
        },
        {
          key: 'TicketType',
          isEnabled: false,
          value: 'Boxed',
          optionsSelected: [],
        },
        {
          key: 'BetAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'PredefinedEntries',
          isEnabled: false,
          value: '5',
          optionsSelected: [],
        },
        {
          key: 'PowerPlay',
          isEnabled: false,
          value: 'False',
          optionsSelected: [],
        },
        {
          key: 'PBAmount',
          isEnabled: false,
          value: '1.00',
          optionsSelected: [],
        },
        {
          key: 'FavoriteDays',
          isEnabled: false,
          value: 'Wednesday',
          optionsSelected: [],
        },
      ],
      areEnabledDraws: true,
    },
    favorites: [
      {
        favoriteId: '6525981a97b928d8097adae2',
        name: 'Pick 3',
        gameType: '3',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '3',
            number4: null,
            number5: null,
          },
          {
            number1: '4',
            number2: '5',
            number3: '6',
            number4: null,
            number5: null,
          },
          {
            number1: '2',
            number2: '3',
            number3: '7',
            number4: null,
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
      {
        favoriteId: '6525981a97b928d8097adae3',
        name: 'Pick 4',
        gameType: '4',
        numbers: [
          {
            number1: '6',
            number2: '5',
            number3: '4',
            number4: '2',
            number5: null,
          },
        ],
        selectionMode: 'inputs',
      },
    ],
  },
]);

db.Settings.insertOne({
  ticketLifeLengthHours: 180,
  ticketPurchaseWindow: 30,
  ticketSequenceNumberUSD: 0,
  ticketSequenceNumberLR: 0,
});

db.Domains.insertMany([
  {
    url: 'betanysports.eu',
    logoutUrl: 'http://someurl',
    lottoSplashWebUrl: '../splash/web/LottoLux.webp',
    lottoSplashMobileUrl: '../splash/mobile/LottoLux.gif',
    lottoRulesUrl: 'http://someurl',
    lucky77Url: 'http://someurl',
    reloadReward: 'http://someurl',
    gameTypes: [
      {
        gameTypeId: '2',
        keyName: 'pick2',
        enabled: true,
        minBet: 0.25,
        maxBet: 1111.11,
        lastChanged: ISODate('1970-01-01T00:00:00.000Z'),
      },
      {
        gameTypeId: '3',
        keyName: 'pick3',
        enabled: true,
        minBet: 0.25,
        maxBet: 111.11,
        lastChanged: ISODate('1970-01-01T00:00:00.000Z'),
      },
      {
        gameTypeId: '4',
        keyName: 'pick4',
        enabled: true,
        minBet: 0.25,
        maxBet: 11.11,
        lastChanged: ISODate('1970-01-01T00:00:00.000Z'),
      },
      {
        gameTypeId: '5',
        keyName: 'pick5',
        enabled: true,
        minBet: 0.25,
        maxBet: 1.11,
        lastChanged: ISODate('1970-01-01T00:00:00.000Z'),
      },
    ],
    enabled: true,
    rewards: [
      {
        _id: 1,
        name: 'Manual',
        currencyCode: 'LR',
      },
      {
        _id: 2,
        name: 'Lucky 77',
        currencyCode: 'LR',
      },
      {
        _id: 3,
        name: 'Reload',
        currencyCode: 'LR',
      },
      {
        _id: 4,
        name: 'Loyalty',
        currencyCode: 'LR',
      },
    ],
  },
]);

db.AdminRoles.insertMany([
  {
    name: 'Help',
    description: 'Help',
  },
  {
    name: 'ToggleStatus',
    description: 'Enable/Disable Status',
  },
  {
    name: 'PromoReport',
    description: 'View Lotto Reward - Promo Report',
  },
  {
    name: 'ManageReload',
    description: 'Deposit/Withdrawal Lotto Reward for L77 and Reload promo',
  },
  {
    name: 'ViewInconsistentTickets',
    description: 'View Inconsistent Ticket Numbers',
  },
  {
    name: 'AddDraw',
    description: 'Add Draws',
  },
  {
    name: 'ViewDraws',
    description: 'View Draws',
  },
  {
    name: 'ViewStates',
    description: 'View States',
  },
  {
    name: 'ResendWinner',
    description: 'Resend Winner',
  },
  {
    name: 'ManageManual',
    description: 'Deposit/Withdrawal Lotto Reward for Manual Promo',
  },
  {
    name: 'ViewGames',
    description: 'View Enabled/Disabled Games',
  },
  {
    name: 'EditStates',
    description: 'Edit States',
  },
  {
    name: 'Powerball',
    description: 'Access anything related to Powerball (unused)',
  },
  {
    name: 'DrawsConfirmation',
    description: 'View Draws Confirmation',
  },
  {
    name: 'ViewUsers',
    description: 'View Users',
  },
  {
    name: 'ToggleGames',
    description: 'Enable/Disable Games',
  },
  {
    name: 'DisabledDraws',
    description: 'View Disabled Draws',
  },
  {
    name: 'GameTypeLimits',
    description: 'View Game Type Limits',
  },
  {
    name: 'ToggleStates',
    description: 'Enable/Disable States',
  },
  {
    name: 'ViewRefund',
    description: 'View Refund',
  },
  {
    name: 'Regrade',
    description: 'Regrade Draws',
  },
  {
    name: 'ConfirmDraw',
    description: 'Confirm Draws',
  },
  {
    name: 'DrawsStatus',
    description: 'View Draws Status',
  },
  {
    name: 'PlayerProfile',
    description: 'View Player Profile',
  },
  {
    name: 'EditProfile',
    description: 'Edit Profile',
  },
  {
    name: 'Reset Profile',
    description: 'Reset Profile',
  },
  {
    name: 'ViewRoles',
    description: 'View Users Roles',
  },
  {
    name: 'DeleteUser',
    description: 'Delete User',
  },
  {
    name: 'ManageDrawLimits',
    description: 'Update max amount limit per draw',
  },
  {
    name: 'SaveProfile',
    description: 'Save Profile',
  },
  {
    name: 'ViewAvatars',
    description: 'View Avatars Approval page',
  },
  {
    name: 'PromoTransactions',
    description: 'View Lotto Reward - Transactions Report',
  },
  {
    name: 'ViewUserRoles',
    description: 'View roles for a user',
  },
  {
    name: 'ManageDomains',
    description: 'Add/Update Domains',
  },
  {
    name: 'Notifications',
    description: 'View Notifications',
  },
  {
    name: 'WinnersReport',
    description: 'View Winners Report',
  },
  {
    name: 'ManageGameTypeLimits',
    description: 'Add/Save Game Type Limits',
  },
  {
    name: 'ManageOfficialSites',
    description: 'Add/Update Official Links for States',
  },
  {
    name: 'AssignRoles',
    description: 'Modify Users Roles',
  },
  {
    name: 'SaveDraw',
    description: 'Save Draw',
  },
  {
    name: 'RemoveSubticket',
    description: 'Remove Subticket',
  },
  {
    name: 'SaveDaysForward',
    description: 'Save Days Forward',
  },
  {
    name: 'TransactionReport',
    description: 'View Transaction Report',
  },
  {
    name: 'DenyAvatar',
    description: 'Deny Avatar',
  },
  {
    name: 'AddProfile',
    description: 'Add Profiles',
  },
  {
    name: 'EnterWinnerNumbers',
    description: 'Enter Winner Numbers on Draws',
  },
  {
    name: 'ToggleBetAmounts',
    description: 'Enable/Disable Bet Amounts',
  },
  {
    name: 'UsersRoles',
    description: 'View Users Roles',
  },
  {
    name: 'ManageDomainMenu',
    description: 'View Manage Domain Menu',
  },
  {
    name: 'ViewProfiles',
    description: 'View Profiles',
  },
  {
    name: 'DrawsLimitReport',
    description: 'View the combination limit report from Draws',
  },
  {
    name: 'ApproveAvatar',
    description: 'Approve Avatar',
  },
  {
    name: 'ViewBetAmounts',
    description: 'View Bet Amounts',
  },
  {
    name: 'ManageLoyalty',
    description: 'Deposit/Withdrawal Lotto Reward for Loyalty promo',
  },
  {
    name: 'StateOnDraws',
    description: 'Add state on Draws Definition',
  },
  {
    name: 'AddRefund',
    description: 'Add Refund',
  },
  {
    name: 'GradingReport',
    description: 'View Grading Report',
  },
  {
    name: 'Devops',
    description: 'Devops',
  },
  {
    name: 'DrawingsReport',
    description: 'View Drawings Report',
  },
  {
    name: 'Grade',
    description: 'Grade Draws',
  },
  {
    name: 'ToggleDomains',
    description: 'Enable/Disable Domains',
  },
  {
    name: 'TicketReport',
    description: 'View Ticket Report',
  },
  {
    name: 'OrphanTicketsReport',
    description: 'View Orphan Tickets Report',
  },
  {
    name: 'RemoveDraw',
    description: 'Remove Draws',
  },
  {
    name: 'DrawsDefinition',
    description: 'View Draws Definition',
  },
  {
    name: 'DeleteNotifications',
    description: 'Delete Notifications',
  },
  {
    name: 'Administrator',
    description: 'Administrator',
  },
  {
    name: 'FinancialReport',
    description: 'View Financial Report',
  },
  {
    name: 'CreateUser',
    description: 'Create Users',
  },
  {
    name: 'RemoveTransaction',
    description: 'Remove Transaction',
  },
  {
    name: 'ManageBetAmounts',
    description: 'Add/Edit Bet Amounts',
  },
  {
    name: 'ViewDrawAmountLimits',
    description: 'View Draw Amount Limits',
  },
  {
    name: 'ViewUser',
    description: 'View a user',
  },
  {
    name: 'AddStates',
    description: 'Add States',
  },
  {
    name: 'ViewOfficialSites',
    description: 'View Draws Official Sites',
  },
  {
    name: 'AvatarsReport',
    description: 'View Avatars Report',
  },
  {
    name: 'Assistant',
    description: 'Assistant',
  },
  {
    name: 'NoAction',
    description: 'Mark grades as No Action',
  },
  {
    name: 'UpdateInconsistentTickets',
    description: 'Update Inconsistent Ticket Numbers',
  },
  {
    name: 'ActivePlayerReport',
    description: 'View Active Player Report',
  },
  {
    name: 'ViewDaysForward',
    description: 'View Manage Days Forward Menu',
  },
  {
    name: 'Support',
    description: 'Support',
  },
  {
    name: 'Impersonate',
    description: 'Allows access to the player site as a specific player - DANGER',
  },
]);

db.States.insertMany([
  {
    abbreviation: 'AC',
    name: 'A. Canada',
    enabled: true,
    link: 'https://www.alc.ca/content/alc/en/our-games/lotto/Lotto4.html',
    log: [],
  },
  {
    abbreviation: 'AR',
    name: 'Arkansas',
    enabled: true,
    link: 'https://www.myarkansaslottery.com',
    log: [],
  },
  {
    abbreviation: 'AZ',
    name: 'Arizona',
    enabled: true,
    link: 'https://www.arizonalottery.com/winning-numbers',
    log: [],
  },
  {
    abbreviation: 'CA',
    name: 'California',
    enabled: true,
    link: 'https://www.calottery.com/win',
    log: [],
  },
  {
    abbreviation: 'CO',
    name: 'Colorado',
    enabled: true,
    link: 'https://www.coloradolottery.com/es/games/pick3/',
    log: [],
  },
  {
    abbreviation: 'CT',
    name: 'Connecticut',
    enabled: true,
    link: 'http://www.ctlottery.org',
    log: [],
  },
  {
    abbreviation: 'DC',
    name: 'Distric of Columbia',
    enabled: true,
    link: 'https://dclottery.com/',
    log: [],
  },
  {
    abbreviation: 'DE',
    name: 'Delaware',
    enabled: true,
    link: 'https://www.delottery.com/',
    log: [],
  },
  {
    abbreviation: 'FL',
    name: 'Florida',
    enabled: true,
    link: 'https://www.flalottery.com/lotto',
    log: [],
  },
  {
    abbreviation: 'GA',
    name: 'Georgia',
    enabled: true,
    link: 'https://www.galottery.com/en-us/winning-numbers.html',
    log: [],
  },
  {
    abbreviation: 'IA',
    name: 'Iowa',
    enabled: true,
    link: 'https://www.ialottery.com/',
    log: [],
  },
  {
    abbreviation: 'ID',
    name: 'Idaho',
    enabled: true,
    link: 'https://www.idaholottery.com/games/draw/pick-3',
    log: [],
  },
  {
    abbreviation: 'IL',
    name: 'Illinois',
    enabled: true,
    link: 'https://www.illinoislottery.com/',
    log: [],
  },
  {
    abbreviation: 'IN',
    name: 'Indiana',
    enabled: true,
    link: 'https://www.hoosierlottery.com/',
    log: [],
  },
  {
    abbreviation: 'KS',
    name: 'Kansas',
    enabled: true,
    link: 'https://www.kslottery.com/',
    log: [],
  },
  {
    abbreviation: 'KY',
    name: 'Kentucky',
    enabled: true,
    link: 'https://www.kylottery.com/apps/',
    log: [],
  },
  {
    abbreviation: 'LA',
    name: 'Louisiana',
    enabled: true,
    link: 'https://louisianalottery.com/winning-numbers',
    log: [],
  },
  {
    abbreviation: 'MA',
    name: 'Massachusetts',
    enabled: true,
    link: 'https://www.masslottery.com/',
    log: [],
  },
  {
    abbreviation: 'MI',
    name: 'Michigan',
    enabled: true,
    link: 'https://www.michiganlottery.com/',
    log: [],
  },
  {
    abbreviation: 'MN',
    name: 'Minnesota',
    enabled: true,
    link: 'https://www.mnlottery.com/',
    log: [],
  },
  {
    abbreviation: 'MO',
    name: 'Missouri',
    enabled: true,
    link: '',
    log: [],
  },
  {
    abbreviation: 'MS',
    name: 'Mississippi',
    enabled: true,
    link: 'https://www.mslotteryhome.com/',
    log: [],
  },
  {
    abbreviation: 'NC',
    name: 'North Carolina',
    enabled: true,
    link: 'https://www.nclottery.com/',
    log: [],
  },
  {
    abbreviation: 'NE',
    name: 'Nebraska',
    enabled: true,
    link: 'https://nelottery.com/homeapp/landing',
    log: [],
  },
  {
    abbreviation: 'NH',
    name: 'New Hampshire',
    enabled: true,
    link: 'https://www.nhlottery.com/',
    log: [],
  },
  {
    abbreviation: 'NJ',
    name: 'New Jersey',
    enabled: true,
    link: 'https://www.njlottery.com/en-us/home.html',
    log: [],
  },
  {
    abbreviation: 'NM',
    name: 'New Mexico',
    enabled: true,
    link: 'https://www.nmlottery.com/',
    log: [],
  },
  {
    abbreviation: 'NY',
    name: 'New York',
    enabled: true,
    link: 'https://nylottery.ny.gov/',
    log: [],
  },
  {
    abbreviation: 'OH',
    name: 'Ohio',
    enabled: true,
    link: 'https://www.ohiolottery.com',
    log: [],
  },
  {
    abbreviation: 'OK',
    name: 'Oklahoma',
    enabled: true,
    link: 'https://www.lottery.ok.gov/',
    log: [],
  },
  {
    abbreviation: 'ON',
    name: 'Ontario',
    enabled: true,
    link: 'https://www.olg.ca/en/lottery/winning-numbers-results.html',
    log: [],
  },
  {
    abbreviation: 'OR',
    name: 'Oregon',
    enabled: true,
    link: 'https://www.oregonlottery.org/pick-4/winning-numbers/ ',
    log: [],
  },
  {
    abbreviation: 'PA',
    name: 'Pennsylvania',
    enabled: true,
    link: 'https://www.palottery.state.pa.us/#tab-1',
    log: [],
  },
  {
    abbreviation: 'PR',
    name: 'Puerto Rico',
    enabled: true,
    link: 'https://loteriasdepuertorico.pr.gov/loteria-electronica/',
    log: [],
  },
  {
    abbreviation: 'QC',
    name: 'Quebec',
    enabled: true,
    link: 'https://loteries.lotoquebec.com/en/home#p=207 ',
    log: [],
  },
  {
    abbreviation: 'RI',
    name: 'Rhode Island',
    enabled: true,
    link: 'https://www.rilot.com/en-us/home.html',
    log: [],
  },
  {
    abbreviation: 'SC',
    name: 'South Carolina',
    enabled: true,
    link: 'http://www.sceducationlottery.com/',
    log: [],
  },
  {
    abbreviation: 'TN',
    name: 'Tennessee',
    enabled: true,
    link: 'https://www.tnlottery.com/',
    log: [],
  },
  {
    abbreviation: 'TX',
    name: 'Texas',
    enabled: true,
    link: 'https://www.txlottery.org/export/sites/lottery/index.html',
    log: [],
  },
  {
    abbreviation: 'VA',
    name: 'Virginia',
    enabled: true,
    link: 'https://www.valottery.com/',
    log: [],
  },
  {
    abbreviation: 'WA',
    name: 'Washington',
    enabled: true,
    link: 'https://www.walottery.com/WinningNumbers/',
    log: [],
  },
  {
    abbreviation: 'WC',
    name: 'W. Canada',
    enabled: true,
    link: 'https://www.wclc.com/home.htm',
    log: [],
  },
  {
    abbreviation: 'WI',
    name: 'Wisconsin',
    enabled: true,
    link: 'https://wilottery.com',
    log: [],
  },
  {
    abbreviation: 'WV',
    name: 'West Virginia',
    enabled: true,
    link: 'https://wvlottery.com',
    log: [],
  },
]);

db.AdminUsers.insertOne({
  username: 'admin',
  email: 'test@test.com',
  firstName: 'admin',
  lastName: 'admin',
  passwordHash: '03ma6iW9/LgsYkn9BnJgWeU2d07an4E4DnIc6YcoNV4=',
  salt: 'sca7zuk1fqYRdPThBh2XXw==',
  temporaryPassword: false,
  enabled: true,
  created: ISODate('1970-01-01T00:00:00.000Z'),
  roles: [
    'DrawsConfirmation',
    'ConfirmDraw',
    'ViewDraws',
    'Grade',
    'Regrade',
    'NoAction',
    'EnterWinnerNumbers',
    'DrawsLimitReport',
    'DrawsDefinition',
    'StateOnDraws',
    'DisabledDraws',
    'AddDraw',
    'RemoveDraw',
    'SaveDraw',
    'DrawsStatus',
    'ToggleStatus',
    'Powerball',
    'ViewBetAmounts',
    'ManageBetAmounts',
    'ToggleBetAmounts',
    'ViewStates',
    'AddStates',
    'ToggleStates',
    'EditStates',
    'ViewOfficialSites',
    'ManageOfficialSites',
    'ViewProfiles',
    'AddProfile',
    'PlayerProfile',
    'SaveProfile',
    'EditProfile',
    'ResetProfile',
    'FinancialReport',
    'WinnersReport',
    'DrawingsReport',
    'TicketReport',
    'TransactionReport',
    'GradingReport',
    'GameTypeLimits',
    'ManageGameTypeLimits',
    'ManageDomainMenu',
    'ManageDomains',
    'ToggleDomains',
    'ViewDaysForward',
    'SaveDaysForward',
    'ViewGames',
    'ToggleGames',
    'ViewDrawAmountLimits',
    'ManageDrawLimits',
    'Notifications',
    'DeleteNotifications',
    'CreateUser',
    'AssignRoles',
    'ViewUsers',
    'DeleteUser',
    'ManageReload',
    'PromoTransactions',
    'PromoReport',
    'ManageManual',
    'ManageLoyalty',
    'ViewAvatars',
    'ApproveAvatar',
    'DenyAvatar',
    'AvatarsReport',
    'ActivePlayerReport',
    'ViewRefund',
    'ResendWinner',
    'RemoveTransaction',
    'RemoveSubticket',
    'Help',
  ],
});

db.WinnersBanner.insertOne({
  topDailyPrize: [],
  topMonthlyPrize: [],
});
