name: London-test

services:
  mongo:
    image: mongo:latest
    container_name: mongo-test-container
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lotto
      MONGO_INITDB_ROOT_PASSWORD: lotto
      MONGO_INITDB_DATABASE: Lotto
    volumes:
      - mongo-test-data:/data/db
      - ./mongo-tools/mongo/init_data.js:/docker-entrypoint-initdb.d/init_data.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  mongo-test-data:
