name: London-test

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-test-container
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lotto
      MONGO_INITDB_ROOT_PASSWORD: lotto
      MONGO_INITDB_DATABASE: Lotto
    volumes:
      - mongo-test-data:/data/db
      - ./mongo-tools/mongo/init_data.js:/docker-entrypoint-initdb.d/init_data.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URL: mongodb://lotto:lotto@mongo:27017/Lotto?authMechanism=SCRAM-SHA-1
    volumes:
      - ./mongo-tools:/app/mongo-tools
    command: bash ./mongo-tools/scripts/run_tests.sh

volumes:
  mongo-test-data:
